#!/usr/bin/env bash
#configures an Nginx server to listen on port 80

#create a symbolic link to enable the default site
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

#Restart Nginx for changes to apply
sudo service nginx restart
